services:
  comfyui:
    build: .
    image: cgl/comfyui
    ports:
      - "8188:8188"
    volumes:
      - "./custom_nodes:/app/custom_nodes"
      - "./models:/app/models"
      - "./outputs:/app/output"
      - "./user:/app/user"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
